# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='arbiter.proto',
  package='proto.agg_web_arbiter',
  serialized_pb='\n\rarbiter.proto\x12\x15proto.agg_web_arbiter\"&\n\x08PBKVPair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\xbf\x03\n\x08ScResult\x12\x0c\n\x04name\x18\x01 \x02(\x0c\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\x0c\x12\n\n\x02id\x18\x03 \x01(\x0c\x12\x0f\n\x07subType\x18\x04 \x01(\x0c\x12\x12\n\ndataSource\x18\x05 \x01(\x0c\x12\x0f\n\x07mainUrl\x18\x06 \x01(\x0c\x12\x11\n\tmainTitle\x18\x07 \x01(\x0c\x12\x0f\n\x07subUrls\x18\x08 \x03(\x0c\x12\x11\n\tsubTitles\x18\t \x03(\x0c\x12\x10\n\x08position\x18\n \x01(\x05\x12\x15\n\rclickFeedback\x18\x0b \x01(\x05\x12\x15\n\rtimeSensitive\x18\x0c \x01(\x05\x12\x11\n\tmakeupPos\x18\r \x01(\x05\x12\x16\n\x0emakeupPriority\x18\x0e \x01(\x05\x12\r\n\x05trace\x18\x0f \x01(\x0c\x12.\n\x05kvMap\x18\x10 \x03(\x0b\x32\x1f.proto.agg_web_arbiter.PBKVPair\x12\x13\n\x0bprocessName\x18\x11 \x01(\x0c\x12\x0e\n\x06spread\x18\x12 \x01(\x0c\x12\x17\n\x0f\x62lurayGroupName\x18\x13 \x01(\x0c\x12\x14\n\x0c\x62lurayIsCore\x18\x14 \x01(\x0c\x12\x0f\n\x07oriName\x18\x15 \x01(\x0c\x12\x0c\n\x04hide\x18\x16 \x01(\x0c\":\n\tCacheInfo\x12\x18\n\x10needRefreshCache\x18\x01 \x01(\x08\x12\x13\n\x0b\x63\x61\x63heScList\x18\x02 \x01(\x0c\"\x98\x03\n\rArbiterResult\x12\r\n\x05trace\x18\x01 \x01(\x0c\x12\x0f\n\x07latency\x18\x02 \x01(\x05\x12\x32\n\tscResults\x18\x03 \x03(\x0b\x32\x1f.proto.agg_web_arbiter.ScResult\x12\x33\n\tcacheInfo\x18\x04 \x01(\x0b\x32 .proto.agg_web_arbiter.CacheInfo\x12\x19\n\x11throwInFilteredSc\x18\x05 \x03(\x0c\x12\x18\n\x10\x62ucketFilteredSc\x18\x06 \x03(\x0c\x12\x1a\n\x12\x64\x65\x61\x64LinkFilteredSc\x18\x07 \x03(\x0c\x12\x1b\n\x13\x62lacklistFilteredSc\x18\x08 \x03(\x0c\x12\x1b\n\x13\x65xclusiveFilteredSc\x18\t \x03(\x0c\x12\x0f\n\x07\x65rrorSc\x18\x14 \x03(\x0c\x12\x15\n\rxmldocerrorSc\x18\x15 \x03(\x0c\x12\x10\n\x08unkownSc\x18\x16 \x03(\x0c\x12\x11\n\ttimeoutSc\x18\x17 \x03(\x0c\x12\x10\n\x08\x63\x61\x63hedSc\x18\x18 \x03(\x0c\x12\x14\n\x0c\x61ppTraceInfo\x18\x19 \x01(\x0c')




_PBKVPAIR = descriptor.Descriptor(
  name='PBKVPair',
  full_name='proto.agg_web_arbiter.PBKVPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='proto.agg_web_arbiter.PBKVPair.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='proto.agg_web_arbiter.PBKVPair.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=78,
)


_SCRESULT = descriptor.Descriptor(
  name='ScResult',
  full_name='proto.agg_web_arbiter.ScResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='proto.agg_web_arbiter.ScResult.name', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='proto.agg_web_arbiter.ScResult.content', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='proto.agg_web_arbiter.ScResult.id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='subType', full_name='proto.agg_web_arbiter.ScResult.subType', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dataSource', full_name='proto.agg_web_arbiter.ScResult.dataSource', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mainUrl', full_name='proto.agg_web_arbiter.ScResult.mainUrl', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mainTitle', full_name='proto.agg_web_arbiter.ScResult.mainTitle', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='subUrls', full_name='proto.agg_web_arbiter.ScResult.subUrls', index=7,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='subTitles', full_name='proto.agg_web_arbiter.ScResult.subTitles', index=8,
      number=9, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='position', full_name='proto.agg_web_arbiter.ScResult.position', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='clickFeedback', full_name='proto.agg_web_arbiter.ScResult.clickFeedback', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timeSensitive', full_name='proto.agg_web_arbiter.ScResult.timeSensitive', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='makeupPos', full_name='proto.agg_web_arbiter.ScResult.makeupPos', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='makeupPriority', full_name='proto.agg_web_arbiter.ScResult.makeupPriority', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='trace', full_name='proto.agg_web_arbiter.ScResult.trace', index=14,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kvMap', full_name='proto.agg_web_arbiter.ScResult.kvMap', index=15,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='processName', full_name='proto.agg_web_arbiter.ScResult.processName', index=16,
      number=17, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='spread', full_name='proto.agg_web_arbiter.ScResult.spread', index=17,
      number=18, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blurayGroupName', full_name='proto.agg_web_arbiter.ScResult.blurayGroupName', index=18,
      number=19, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blurayIsCore', full_name='proto.agg_web_arbiter.ScResult.blurayIsCore', index=19,
      number=20, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='oriName', full_name='proto.agg_web_arbiter.ScResult.oriName', index=20,
      number=21, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hide', full_name='proto.agg_web_arbiter.ScResult.hide', index=21,
      number=22, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=81,
  serialized_end=528,
)


_CACHEINFO = descriptor.Descriptor(
  name='CacheInfo',
  full_name='proto.agg_web_arbiter.CacheInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='needRefreshCache', full_name='proto.agg_web_arbiter.CacheInfo.needRefreshCache', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cacheScList', full_name='proto.agg_web_arbiter.CacheInfo.cacheScList', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=530,
  serialized_end=588,
)


_ARBITERRESULT = descriptor.Descriptor(
  name='ArbiterResult',
  full_name='proto.agg_web_arbiter.ArbiterResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='trace', full_name='proto.agg_web_arbiter.ArbiterResult.trace', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='latency', full_name='proto.agg_web_arbiter.ArbiterResult.latency', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='scResults', full_name='proto.agg_web_arbiter.ArbiterResult.scResults', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cacheInfo', full_name='proto.agg_web_arbiter.ArbiterResult.cacheInfo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='throwInFilteredSc', full_name='proto.agg_web_arbiter.ArbiterResult.throwInFilteredSc', index=4,
      number=5, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bucketFilteredSc', full_name='proto.agg_web_arbiter.ArbiterResult.bucketFilteredSc', index=5,
      number=6, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='deadLinkFilteredSc', full_name='proto.agg_web_arbiter.ArbiterResult.deadLinkFilteredSc', index=6,
      number=7, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blacklistFilteredSc', full_name='proto.agg_web_arbiter.ArbiterResult.blacklistFilteredSc', index=7,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='exclusiveFilteredSc', full_name='proto.agg_web_arbiter.ArbiterResult.exclusiveFilteredSc', index=8,
      number=9, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorSc', full_name='proto.agg_web_arbiter.ArbiterResult.errorSc', index=9,
      number=20, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='xmldocerrorSc', full_name='proto.agg_web_arbiter.ArbiterResult.xmldocerrorSc', index=10,
      number=21, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unkownSc', full_name='proto.agg_web_arbiter.ArbiterResult.unkownSc', index=11,
      number=22, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timeoutSc', full_name='proto.agg_web_arbiter.ArbiterResult.timeoutSc', index=12,
      number=23, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cachedSc', full_name='proto.agg_web_arbiter.ArbiterResult.cachedSc', index=13,
      number=24, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='appTraceInfo', full_name='proto.agg_web_arbiter.ArbiterResult.appTraceInfo', index=14,
      number=25, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=591,
  serialized_end=999,
)

_SCRESULT.fields_by_name['kvMap'].message_type = _PBKVPAIR
_ARBITERRESULT.fields_by_name['scResults'].message_type = _SCRESULT
_ARBITERRESULT.fields_by_name['cacheInfo'].message_type = _CACHEINFO
DESCRIPTOR.message_types_by_name['PBKVPair'] = _PBKVPAIR
DESCRIPTOR.message_types_by_name['ScResult'] = _SCRESULT
DESCRIPTOR.message_types_by_name['CacheInfo'] = _CACHEINFO
DESCRIPTOR.message_types_by_name['ArbiterResult'] = _ARBITERRESULT

class PBKVPair(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBKVPAIR
  
  # @@protoc_insertion_point(class_scope:proto.agg_web_arbiter.PBKVPair)

class ScResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCRESULT
  
  # @@protoc_insertion_point(class_scope:proto.agg_web_arbiter.ScResult)

class CacheInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CACHEINFO
  
  # @@protoc_insertion_point(class_scope:proto.agg_web_arbiter.CacheInfo)

class ArbiterResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ARBITERRESULT
  
  # @@protoc_insertion_point(class_scope:proto.agg_web_arbiter.ArbiterResult)

# @@protoc_insertion_point(module_scope)
