# -*- mode: python -*-

Import('env')
env = env.Clone()

cpps = Glob('*.cpp')

cpps += env.aDirs('common')
cpps += env.aDirs('data')
cpps += env.aDirs('helper')
cpps += env.aDirs('loader')
cpps += env.aDirs('util')
cpps += env.aDirs('upstream')
cpps += env.aDirs('proto')
cpps += env.aDirs('biz')
env.aSharedLibrary(target = 'a4_agg_web2',
             source = cpps,
             LIBS = env['agg2_base_libs'] + env['common_libs'],
             LIBATTRS = {'NlpToolkit': 'static'},
             dirInPackage = 'lib64')
