# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='matrix_feature.proto',
  package='A8.ufs_client.proto.feature',
  serialized_pb='\n\x14matrix_feature.proto\x12\x1b\x41\x38.ufs_client.proto.feature\"\xa9\x01\n\x07\x45lement\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32(.A8.ufs_client.proto.feature.ElementType\x12\x12\n\nbool_value\x18\x02 \x01(\x08\x12\x11\n\tint_value\x18\x03 \x01(\x12\x12\x14\n\x0c\x64ouble_value\x18\x04 \x01(\x01\x12\x14\n\x0cstring_value\x18\x05 \x01(\t\x12\x13\n\x0b\x62ytes_value\x18\x06 \x01(\x0c\"\x7f\n\x05\x41rray\x12>\n\x0c\x65lement_type\x18\x01 \x01(\x0e\x32(.A8.ufs_client.proto.feature.ElementType\x12\x36\n\x08\x65lements\x18\x02 \x03(\x0b\x32$.A8.ufs_client.proto.feature.Element\"~\n\x08Matrix2D\x12>\n\x0c\x65lement_type\x18\x01 \x01(\x0e\x32(.A8.ufs_client.proto.feature.ElementType\x12\x32\n\x06\x61rrays\x18\x02 \x03(\x0b\x32\".A8.ufs_client.proto.feature.Array\"\x84\x01\n\x08Matrix3D\x12>\n\x0c\x65lement_type\x18\x01 \x01(\x0e\x32(.A8.ufs_client.proto.feature.ElementType\x12\x38\n\tmatrix2ds\x18\x02 \x03(\x0b\x32%.A8.ufs_client.proto.feature.Matrix2D\"\xfa\x01\n\x06Matrix\x12\x0b\n\x03\x64im\x18\x01 \x01(\x05\x12>\n\x0c\x65lement_type\x18\x02 \x01(\x0e\x32(.A8.ufs_client.proto.feature.ElementType\x12\x31\n\x05\x61rray\x18\x03 \x01(\x0b\x32\".A8.ufs_client.proto.feature.Array\x12\x37\n\x08matrix2d\x18\x04 \x01(\x0b\x32%.A8.ufs_client.proto.feature.Matrix2D\x12\x37\n\x08matrix3d\x18\x05 \x01(\x0b\x32%.A8.ufs_client.proto.feature.Matrix3D*m\n\x0b\x45lementType\x12\x08\n\x04\x42OOL\x10\x00\x12\x07\n\x03INT\x10\x01\x12\n\n\x06\x44OUBLE\x10\x02\x12\n\n\x06STRING\x10\x03\x12\t\n\x05\x42YTES\x10\x04\x12\x0c\n\x08\x45XTEND_1\x10\x05\x12\x0c\n\x08\x45XTEND_2\x10\x06\x12\x0c\n\x08\x45XTEND_3\x10\x07')

_ELEMENTTYPE = descriptor.EnumDescriptor(
  name='ElementType',
  full_name='A8.ufs_client.proto.feature.ElementType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='BOOL', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INT', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DOUBLE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STRING', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BYTES', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXTEND_1', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXTEND_2', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXTEND_3', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=870,
  serialized_end=979,
)


BOOL = 0
INT = 1
DOUBLE = 2
STRING = 3
BYTES = 4
EXTEND_1 = 5
EXTEND_2 = 6
EXTEND_3 = 7



_ELEMENT = descriptor.Descriptor(
  name='Element',
  full_name='A8.ufs_client.proto.feature.Element',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='A8.ufs_client.proto.feature.Element.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bool_value', full_name='A8.ufs_client.proto.feature.Element.bool_value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='int_value', full_name='A8.ufs_client.proto.feature.Element.int_value', index=2,
      number=3, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='double_value', full_name='A8.ufs_client.proto.feature.Element.double_value', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='string_value', full_name='A8.ufs_client.proto.feature.Element.string_value', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bytes_value', full_name='A8.ufs_client.proto.feature.Element.bytes_value', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=223,
)


_ARRAY = descriptor.Descriptor(
  name='Array',
  full_name='A8.ufs_client.proto.feature.Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='element_type', full_name='A8.ufs_client.proto.feature.Array.element_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='elements', full_name='A8.ufs_client.proto.feature.Array.elements', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=225,
  serialized_end=352,
)


_MATRIX2D = descriptor.Descriptor(
  name='Matrix2D',
  full_name='A8.ufs_client.proto.feature.Matrix2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='element_type', full_name='A8.ufs_client.proto.feature.Matrix2D.element_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='arrays', full_name='A8.ufs_client.proto.feature.Matrix2D.arrays', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=354,
  serialized_end=480,
)


_MATRIX3D = descriptor.Descriptor(
  name='Matrix3D',
  full_name='A8.ufs_client.proto.feature.Matrix3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='element_type', full_name='A8.ufs_client.proto.feature.Matrix3D.element_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='matrix2ds', full_name='A8.ufs_client.proto.feature.Matrix3D.matrix2ds', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=483,
  serialized_end=615,
)


_MATRIX = descriptor.Descriptor(
  name='Matrix',
  full_name='A8.ufs_client.proto.feature.Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dim', full_name='A8.ufs_client.proto.feature.Matrix.dim', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='element_type', full_name='A8.ufs_client.proto.feature.Matrix.element_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='array', full_name='A8.ufs_client.proto.feature.Matrix.array', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='matrix2d', full_name='A8.ufs_client.proto.feature.Matrix.matrix2d', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='matrix3d', full_name='A8.ufs_client.proto.feature.Matrix.matrix3d', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=618,
  serialized_end=868,
)

_ELEMENT.fields_by_name['type'].enum_type = _ELEMENTTYPE
_ARRAY.fields_by_name['element_type'].enum_type = _ELEMENTTYPE
_ARRAY.fields_by_name['elements'].message_type = _ELEMENT
_MATRIX2D.fields_by_name['element_type'].enum_type = _ELEMENTTYPE
_MATRIX2D.fields_by_name['arrays'].message_type = _ARRAY
_MATRIX3D.fields_by_name['element_type'].enum_type = _ELEMENTTYPE
_MATRIX3D.fields_by_name['matrix2ds'].message_type = _MATRIX2D
_MATRIX.fields_by_name['element_type'].enum_type = _ELEMENTTYPE
_MATRIX.fields_by_name['array'].message_type = _ARRAY
_MATRIX.fields_by_name['matrix2d'].message_type = _MATRIX2D
_MATRIX.fields_by_name['matrix3d'].message_type = _MATRIX3D
DESCRIPTOR.message_types_by_name['Element'] = _ELEMENT
DESCRIPTOR.message_types_by_name['Array'] = _ARRAY
DESCRIPTOR.message_types_by_name['Matrix2D'] = _MATRIX2D
DESCRIPTOR.message_types_by_name['Matrix3D'] = _MATRIX3D
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX

class Element(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ELEMENT
  
  # @@protoc_insertion_point(class_scope:A8.ufs_client.proto.feature.Element)

class Array(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ARRAY
  
  # @@protoc_insertion_point(class_scope:A8.ufs_client.proto.feature.Array)

class Matrix2D(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MATRIX2D
  
  # @@protoc_insertion_point(class_scope:A8.ufs_client.proto.feature.Matrix2D)

class Matrix3D(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MATRIX3D
  
  # @@protoc_insertion_point(class_scope:A8.ufs_client.proto.feature.Matrix3D)

class Matrix(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MATRIX
  
  # @@protoc_insertion_point(class_scope:A8.ufs_client.proto.feature.Matrix)

# @@protoc_insertion_point(module_scope)
