# -*- mode: python -*-

Import('env')
env = env.Clone()

#env.aDirs('test')

cpps = Glob('*.cpp')
cpps += env.aDirs('general_llm')
cpps += env.aDirs('common')
cpps += env.aDirs('trigger')
cpps += env.aDirs('recall')
cpps += env.aDirs('rank')
cpps += env.aDirs('llm')
cpps += env.aDirs('qlog')
cpps += env.aDirs('mount')
cpps += env.aDirs('debug')
cpps += env.aDirs('academic_recall')
Return(['cpps'])
