# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='ProxyResult.proto',
  package='zeus.BatchRequestProxy',
  serialized_pb='\n\x11ProxyResult.proto\x12\x16zeus.BatchRequestProxy\"/\n\tAppResult\x12\x0f\n\x07\x61ppName\x18\x01 \x01(\t\x12\x11\n\tresultStr\x18\x02 \x01(\x0c\"\xa2\x01\n\x0bProxyResult\x12\x34\n\tappResult\x18\x01 \x03(\x0b\x32!.zeus.BatchRequestProxy.AppResult\x12\x17\n\x0funknownAppNames\x18\x02 \x03(\x0c\x12\x15\n\rerrorAppNames\x18\x03 \x03(\x0c\x12\x17\n\x0ftimeoutAppNames\x18\x04 \x03(\x0c\x12\x14\n\x0c\x61ppTraceInfo\x18\x05 \x01(\x0c')




_APPRESULT = descriptor.Descriptor(
  name='AppResult',
  full_name='zeus.BatchRequestProxy.AppResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='appName', full_name='zeus.BatchRequestProxy.AppResult.appName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resultStr', full_name='zeus.BatchRequestProxy.AppResult.resultStr', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=92,
)


_PROXYRESULT = descriptor.Descriptor(
  name='ProxyResult',
  full_name='zeus.BatchRequestProxy.ProxyResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='appResult', full_name='zeus.BatchRequestProxy.ProxyResult.appResult', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unknownAppNames', full_name='zeus.BatchRequestProxy.ProxyResult.unknownAppNames', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorAppNames', full_name='zeus.BatchRequestProxy.ProxyResult.errorAppNames', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timeoutAppNames', full_name='zeus.BatchRequestProxy.ProxyResult.timeoutAppNames', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='appTraceInfo', full_name='zeus.BatchRequestProxy.ProxyResult.appTraceInfo', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=95,
  serialized_end=257,
)

_PROXYRESULT.fields_by_name['appResult'].message_type = _APPRESULT
DESCRIPTOR.message_types_by_name['AppResult'] = _APPRESULT
DESCRIPTOR.message_types_by_name['ProxyResult'] = _PROXYRESULT

class AppResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _APPRESULT
  
  # @@protoc_insertion_point(class_scope:zeus.BatchRequestProxy.AppResult)

class ProxyResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROXYRESULT
  
  # @@protoc_insertion_point(class_scope:zeus.BatchRequestProxy.ProxyResult)

# @@protoc_insertion_point(module_scope)
