alog.rootLogger=ERROR
alog.max_msg_len=98304

alog.appender.cygnetAppender=FileAppender
alog.appender.cygnetAppender.fileName=cygnet.log
alog.appender.cygnetAppender.max_file_size=1024
alog.appender.cygnetAppender.delay_time=1
alog.appender.cygnetAppender.flush=false
alog.appender.cygnetAppender.async_flush=true
alog.appender.cygnetAppender.flush_threshold=1
alog.appender.cygnetAppender.flush_interval=1000
alog.appender.cygnetAppender.layout=PatternLayout
alog.appender.cygnetAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.cygnetAppender.log_keep_count=10

alog.appender.A4Appender=FileAppender
alog.appender.A4Appender.fileName=A4.log
alog.appender.A4Appender.max_file_size=1024
alog.appender.A4Appender.delay_time=1
alog.appender.A4Appender.flush=false
alog.appender.A4Appender.async_flush=true
alog.appender.A4Appender.flush_threshold=1
alog.appender.A4Appender.flush_interval=1000
alog.appender.A4Appender.layout=PatternLayout
alog.appender.A4Appender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.A4Appender.log_keep_count=6

alog.appender.NsAppender=FileAppender
alog.appender.NsAppender.fileName=ns.log
alog.appender.NsAppender.max_file_size=1024
alog.appender.NsAppender.delay_time=1
alog.appender.NsAppender.flush=false
alog.appender.NsAppender.async_flush=true
alog.appender.NsAppender.flush_threshold=1
alog.appender.NsAppender.flush_interval=1000
alog.appender.NsAppender.layout=PatternLayout
alog.appender.NsAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.NsAppender.log_keep_count=48

alog.appender.anetAppender=FileAppender
alog.appender.anetAppender=FileAppender
alog.appender.anetAppender.fileName=anet.log
alog.appender.anetAppender.max_file_size=1024
alog.appender.anetAppender.delay_time=1
alog.appender.anetAppender.flush=false
alog.appender.anetAppender.async_flush=true
alog.appender.anetAppender.flush_threshold=1
alog.appender.anetAppender.flush_interval=1000
alog.appender.anetAppender.layout=PatternLayout
alog.appender.anetAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.anetAppender.log_keep_count=10

alog.appender.agg_webAppender=FileAppender
alog.appender.agg_webAppender.fileName=agg_web.log
alog.appender.agg_webAppender.max_file_size=1024
alog.appender.agg_webAppender.delay_time=1
alog.appender.agg_webAppender.flush=false
alog.appender.agg_webAppender.async_flush=true
alog.appender.agg_webAppender.flush_threshold=1
alog.appender.agg_webAppender.flush_interval=1000
alog.appender.agg_webAppender.layout=PatternLayout
alog.appender.agg_webAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.agg_webAppender.log_keep_count=40

alog.appender.agg_web2Appender=FileAppender
alog.appender.agg_web2Appender.fileName=agg_web2.log
alog.appender.agg_web2Appender.max_file_size=1024
alog.appender.agg_web2Appender.delay_time=1
alog.appender.agg_web2Appender.flush=false
alog.appender.agg_web2Appender.async_flush=true
alog.appender.agg_web2Appender.flush_threshold=1
alog.appender.agg_web2Appender.flush_interval=1000
alog.appender.agg_web2Appender.layout=PatternLayout
alog.appender.agg_web2Appender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.agg_web2Appender.log_keep_count=40

alog.appender.intentionLogAppender=FileAppender
alog.appender.intentionLogAppender.fileName=intention.log
alog.appender.intentionLogAppender.max_file_size=1024
alog.appender.intentionLogAppender.delay_time=1
alog.appender.intentionLogAppender.flush=false
alog.appender.intentionLogAppender.async_flush=true
alog.appender.intentionLogAppender.flush_threshold=1
alog.appender.intentionLogAppender.flush_interval=1000
alog.appender.intentionLogAppender.layout=PatternLayout
alog.appender.intentionLogAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.intentionLogAppender.log_keep_count=2

alog.appender.ScAolLogAppender=FileAppender
alog.appender.ScAolLogAppender.fileName=ScAol.log
alog.appender.ScAolLogAppender.max_file_size=1024
alog.appender.ScAolLogAppender.delay_time=1
alog.appender.ScAolLogAppender.flush=false
alog.appender.ScAolLogAppender.async_flush=true
alog.appender.ScAolLogAppender.flush_threshold=1
alog.appender.ScAolLogAppender.flush_interval=1000
alog.appender.ScAolLogAppender.layout=PatternLayout
alog.appender.ScAolLogAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.ScAolLogAppender.log_keep_count=32

alog.appender.allStageLogAppender=FileAppender
alog.appender.allStageLogAppender.fileName=allStage.log
alog.appender.allStageLogAppender.max_file_size=1024
alog.appender.allStageLogAppender.delay_time=1
alog.appender.allStageLogAppender.flush=false
alog.appender.allStageLogAppender.async_flush=true
alog.appender.allStageLogAppender.flush_threshold=1
alog.appender.allStageLogAppender.flush_interval=1000
alog.appender.allStageLogAppender.layout=PatternLayout
alog.appender.allStageLogAppender.layout.LogPattern=%%m
alog.appender.allStageLogAppender.log_keep_count=12

alog.appender.traceLogAppender=FileAppender
alog.appender.traceLogAppender.fileName=trace.log
alog.appender.traceLogAppender.max_file_size=1024
alog.appender.traceLogAppender.delay_time=1
alog.appender.traceLogAppender.flush=false
alog.appender.traceLogAppender.async_flush=true
alog.appender.traceLogAppender.flush_threshold=1
alog.appender.traceLogAppender.flush_interval=1000
alog.appender.traceLogAppender.layout=PatternLayout
alog.appender.traceLogAppender.layout.LogPattern=%%m
alog.appender.traceLogAppender.log_keep_count=100

alog.appender.displayLogAppender=FileAppender
alog.appender.displayLogAppender.fileName=displayUrls.log
alog.appender.displayLogAppender.max_file_size=1024
alog.appender.displayLogAppender.delay_time=1
alog.appender.displayLogAppender.flush=false
alog.appender.displayLogAppender.async_flush=true
alog.appender.displayLogAppender.flush_threshold=1
alog.appender.displayLogAppender.flush_interval=1000
alog.appender.displayLogAppender.layout=PatternLayout
alog.appender.displayLogAppender.layout.LogPattern=%%m
alog.appender.displayLogAppender.log_keep_count=90

alog.appender.monitorLogAppender=FileAppender
alog.appender.monitorLogAppender.fileName=monitor.log
alog.appender.monitorLogAppender.max_file_size=1024
alog.appender.monitorLogAppender.delay_time=1
alog.appender.monitorLogAppender.flush=false
alog.appender.monitorLogAppender.async_flush=true
alog.appender.monitorLogAppender.flush_threshold=1
alog.appender.monitorLogAppender.flush_interval=1000
alog.appender.monitorLogAppender.layout=PatternLayout
alog.appender.monitorLogAppender.layout.LogPattern=%%m
alog.appender.monitorLogAppender.log_keep_count=20

alog.appender.aggAppender=FileAppender
alog.appender.aggAppender.fileName=agg.log
alog.appender.aggAppender.max_file_size=1024
alog.appender.aggAppender.delay_time=1
alog.appender.aggAppender.flush=false
alog.appender.aggAppender.async_flush=true
alog.appender.aggAppender.flush_threshold=1
alog.appender.aggAppender.flush_interval=1000
alog.appender.aggAppender.layout=PatternLayout
alog.appender.aggAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.aggAppender.log_keep_count=48

alog.appender.accessAppender=FileAppender
alog.appender.accessAppender.fileName=access.log
alog.appender.accessAppender.max_file_size=1024
alog.appender.accessAppender.delay_time=1
alog.appender.accessAppender.flush=false
alog.appender.accessAppender.async_flush=true
alog.appender.accessAppender.flush_threshold=1
alog.appender.accessAppender.flush_interval=1000
alog.appender.accessAppender.layout=PatternLayout
alog.appender.accessAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.accessAppender.log_keep_count=40

alog.appender.straceAppender=FileAppender
alog.appender.straceAppender.fileName=strace.log
alog.appender.straceAppender.max_file_size=1024
alog.appender.straceAppender.delay_time=1
alog.appender.straceAppender.flush=false
alog.appender.straceAppender.async_flush=true
alog.appender.straceAppender.flush_threshold=1
alog.appender.straceAppender.flush_interval=1000
alog.appender.straceAppender.layout=PatternLayout
alog.appender.straceAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.straceAppender.log_keep_count=10

alog.appender.utraceAppender=FileAppender
alog.appender.utraceAppender.fileName=utrace.log
alog.appender.utraceAppender.max_file_size=1024
alog.appender.utraceAppender.delay_time=1
alog.appender.utraceAppender.flush=false
alog.appender.utraceAppender.async_flush=true
alog.appender.utraceAppender.flush_threshold=1
alog.appender.utraceAppender.flush_interval=1000
alog.appender.utraceAppender.layout=PatternLayout
alog.appender.utraceAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.utraceAppender.log_keep_count=5

alog.appender.umetricAppender=FileAppender
alog.appender.umetricAppender.fileName=umetrics.log
alog.appender.umetricAppender.max_file_size=1024
alog.appender.umetricAppender.delay_time=1
alog.appender.umetricAppender.flush=false
alog.appender.umetricAppender.async_flush=true
alog.appender.umetricAppender.flush_threshold=1
alog.appender.umetricAppender.flush_interval=1000
alog.appender.umetricAppender.layout=PatternLayout
alog.appender.umetricAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.umetricAppender.log_keep_count=5

alog.appender.bucketInfoLogAppender=FileAppender
alog.appender.bucketInfoLogAppender.fileName=bucketInfoLog.log
alog.appender.bucketInfoLogAppender.max_file_size=1024
alog.appender.bucketInfoLogAppender.delay_time=1
alog.appender.bucketInfoLogAppender.flush=false
alog.appender.bucketInfoLogAppender.async_flush=true
alog.appender.bucketInfoLogAppender.flush_threshold=1
alog.appender.bucketInfoLogAppender.flush_interval=1000
alog.appender.bucketInfoLogAppender.layout=PatternLayout
alog.appender.bucketInfoLogAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.bucketInfoLogAppender.log_keep_count=6

alog.appender.bucketInfoAppender=FileAppender
alog.appender.bucketInfoAppender.fileName=bucketInfo.log
alog.appender.bucketInfoAppender.max_file_size=1024
alog.appender.bucketInfoAppender.delay_time=1
alog.appender.bucketInfoAppender.flush=false
alog.appender.bucketInfoAppender.async_flush=true
alog.appender.bucketInfoAppender.flush_threshold=1
alog.appender.bucketInfoAppender.flush_interval=1000
alog.appender.bucketInfoAppender.layout=PatternLayout
alog.appender.bucketInfoAppender.layout.LogPattern=[%%d %%l %%t %%F:%%n] %%m
alog.appender.bucketInfoAppender.log_keep_count=6


alog.logger.anet=ERROR, anetAppender
alog.logger.cygnet=ERROR, cygnetAppender
alog.logger.strace.strace_client=ERROR, straceAppender
alog.logger.umonitor.trace=ERROR, utraceAppender
alog.logger.umonitor.metrics=ERROR, umetricAppender
alog.logger.GigUtil=ERROR, A4Appender
alog.logger.multi_call=ERROR, A4Appender
alog.logger.A4.common=ERROR, A4Appender
alog.logger.A4.config=ERROR, A4Appender
alog.logger.A4.util=ERROR, A4Appender
alog.logger.A4.upstream=ERROR, A4Appender
alog.logger.A4.network=ERROR, A4Appender
alog.logger.A4.processor=ERROR, A4Appender
alog.logger.A4.app_selector=ERROR, A4Appender
alog.logger.A4.wrapper=ERROR, A4Appender
alog.logger.A4.data_engine=ERROR, A4Appender
alog.logger.A4.service=ERROR, A4Appender
alog.logger.A4.monitor=ERROR, A4Appender
alog.logger.A4.module=ERROR, A4Appender
alog.logger.A4.ns_plugin=ERROR, NsAppender

alog.logger.A4.access=INFO, accessAppender

alog.logger.A8.ufs_client=ERROR, agg_webAppender

alog.logger.Agg.common=ERROR, agg_webAppender
alog.logger.Agg.biz=ERROR, agg_webAppender
alog.logger.Agg.data=ERROR, agg_webAppender
alog.logger.Agg.debuger=ERROR, agg_webAppender
alog.logger.Agg.helper=ERROR, agg_webAppender
alog.logger.Agg.loader=ERROR, agg_webAppender
alog.logger.Agg.merger=ERROR, agg_webAppender
alog.logger.Agg.model=ERROR, agg_webAppender
alog.logger.Agg.processor=INFO, agg_webAppender
alog.logger.Agg.selector=ERROR, agg_webAppender
alog.logger.Agg.upstream=ERROR, agg_webAppender
alog.logger.Agg.wrapper=ERROR, agg_webAppender
alog.logger.Agg.util=ERROR, agg_webAppender
alog.logger.Agg.bucketInfoLog=INFO, bucketInfoLogAppender
alog.logger.Agg.bucketInfo=INFO, bucketInfoAppender

alog.logger.Agg.displayLog=INFO, displayLogAppender
alog.logger.Agg.monitorLog=INFO, monitorLogAppender
alog.logger.Agg.intentionLog=INFO, intentionLogAppender
alog.logger.Agg.ScAolLog=INFO, ScAolLogAppender
alog.logger.Agg.allStageLog=INFO, allStageLogAppender
alog.logger.Agg.traceLog=INFO, traceLogAppender

alog.logger.Agg.agg_web2=INFO, agg_webAppender
alog.logger.Agg.agg_web=INFO, agg_webAppender
